[phases.setup]
nixPkgs = ["libmagic", "pango", "harfbuzz", "shared-mime-info"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "sh -c 'uvicorn main:app --host 0.0.0.0 --port $PORT'"
